### PR TITLE
Contact components

### LINKED ISSUE #5: Create the ShowContacts component
Functionality: 
- [x] Get the data from the list of contacts
- [x] Display the data
- [x] Each contact is clickable and will display in a different component.
- [x] have an add button on the page 
- [x] have a delete option for each contact
- [x] have an update option for each contact 

Nice to haves:
- [ ]  create a scroll bar with alphabets.
- [ ]  have a button to scroll all the way back up.

### LINKED ISSUE #6: Create AddContact form
A form that has these things:
- [ ]  can submit a new contact
- [ ]  a couple of required fields
- [ ]  a couple fields that aren't required
- [ ]  updates the database table
- [ ] display everything automatically.
- [ ] Use HTML input attributes to validate input and make entering data fast and easy
- [ ] Show a user-visible error message to indicate what's wrong and how the user can fix it

### LINKED ISSUE #7: Edit contact in the contact form
In the contact form, allow the user to select an existing contact and edit it.

### LINKED ISSUE #8: Add a delete button and functionality
Add a delete button in: 
- [ ] at every contact displayed
- [ ] when I open up to it's own individual contact, have an delete option

### LINKED ISSUE #9: Add ContatDetails Component
- [ ] Display all of the contact's information

- [ ] Edit button
- [ ] Delete button
- [ ] Exit button to return to the main page

### LINKED ISSUE #12: Edit button in the main screen
in the main screen where all names are displayed, put it in front of the contact name, when clicked, pull up contact form and populate form with existing contact information.

### LINKED ISSUE #13: Edit Button in the Contact Details
when opening up to individual contact name, add an edit button too when clicked, pull up contact form and populate form with existing contact information.

### PR DESCRIPTION
**Pull request by wk642**
ContactList:
- [ ] displays the contacts
- [ ] has add button
- [ ] has delete buttons
- [ ] has edit buttons
- [ ] when click on it, it will open up another display to display the details of contacts

ContactDetails:
- [ ] displays all the details
- [ ] show and hides ids
- [ ] different screen size will display differently (small vs middle and large)

ContactForm:
- [ ] has add 
- [ ] has edit
- [ ] both functioning 
- [ ] !! wanted this to be like a tab and user can switch between the two, but it messes up for when I'm in edit, it will still edit even after I switch to add, so switched up the design for now. Creating an issue for this

### CODE REVIEW

File: client/src/components/ContactDetails.jsx [hunk 1]
```diff
@@ -0,0 +1,76 @@
...
+          <p className="text-slate-300">
+            <strong>Group ID:</strong> {selectedContact.group_id}
+          </p>
+        </div>
+      )}
+    </div>
+  );
+}
+
+export default ContactDetails;
```
Comment (efalsken) [inline client/src/components/ContactDetails.jsx:76]: usually people put the export at the top, near the imports.

File: client/src/components/ContactList.jsx [hunk 2]
```diff
@@ -0,0 +1,276 @@
...
+    // all the contacts
+    fetch("http://localhost:5000/contacts") 
+      .then((response) => {
+        if (!response.ok) {
+          throw new Error(`HTTP error! status: ${response.status}`);
+        }
+        return response.json();
+      })
+      .then((data) => {
+        console.log("Data from backend:", data);
```
Comment (efalsken) [inline client/src/components/ContactList.jsx:28]: put the name of the api here:
```
console.log("GET", url, request);
fetch(url, request).then(response => {
  console.log("GET", url, response);
});
```
This way you can see which log messages go with which requests. This will be very useful when you have multiple long-running api calls going on at the same time, and some of them will return earlier than others.

File: client/src/components/ContactList.jsx [hunk 3]
```diff
@@ -0,0 +1,276 @@
...
+        const emojis = {};
+        data.forEach((contact) => {
+          emojis[contact.id] = getRandomEmoji();
+        });
+        setContactEmojis(emojis);
+        setContacts(data);
+        setLoading(false);
+      })
+      .catch((err) => {
+        setError(err);
```
Comment (efalsken) [inline client/src/components/ContactList.jsx:40]: forgot to `console.error(err)`

File: client/src/components/ContactList.jsx [hunk 4]
```diff
@@ -0,0 +1,276 @@
...
+            data.forEach((contact) => {
+              emojis[contact.id] = getRandomEmoji();
+            });
+            setContactEmojis(emojis);
+            setContacts(data);
+          });
+        setShowForm(false);
+      })
+      .catch((error) => {
+        console.error("Error adding contact:", error);
```
Comment (efalsken) [inline client/src/components/ContactList.jsx:107]: you are using seterror() in some places, but console.error sometimes. Should be consistent. You can create a function:

```
function handleException(err){
  console.error(err);
  seterror(err)
}
function handleFetchError(errResponse){
  // same thing, but for a fetch response
}
```
